server/users/forms.py
from flask_wtf import FlaskForm
from wtforms import TextField, PasswordField
from wtforms.validators import DataRequired, Length, Email, EqualTo


class LoginForm(FlaskForm):
    username = TextField("Login", validators=[DataRequired(), Length(min=6, max=20)])
    password = PasswordField("Password", validators=[DataRequired(), Length(min=6, max=48)])


class RegisterForm(FlaskForm):
    username = TextField("Login", validators=[DataRequired(), Length(min=6, max=20)])
    email = TextField("Email", validators=[DataRequired(), Email()])
    password = PasswordField(
        "Password", validators=[DataRequired(), Length(min=6, max=48)]
    )
    confirm = PasswordField(
        "Repeat Password", validators=[DataRequired(), EqualTo("password")]
    )
    fullname = TextField("Full Name", validators=[DataRequired()])

server/configs/__init__.py
from .views import configs_blueprint


__all__ = ["configs_blueprint"]

server/configs/views.py
from flask import Blueprint


configs_blueprint = Blueprint('configs', __name__, url_prefix='/configs')


@configs_blueprint.route("/", methods=["GEt"])
def configs_list():
    pass

server/database/__init__.py
from .abstract_database import AbstractDatabase, read_db_config_from_envs
from .postgres import PostgresDatabase


__all__ = [
    'read_db_config_from_envs',
    'AbstractDatabase',
    'PostgresDatabase'
]

server/services/__init__.py
from .views import services_blueprint


__all__ = ['services_blueprint']

server/services/views.py
from flask import Blueprint, render_template


services_blueprint = Blueprint('services', __name__, url_prefix='/services')


@services_blueprint.route("/", methods=["GET"])
def services_list():
    return render_template('services/services.html')


@services_blueprint.route("/add", methods=["GET", "POST"])
def services_add():
    pass


@services_blueprint.route("/remove", methods=["POST"])
def remove_service():
    pass

server/users/views.py
from typing import Optional
from flask_login import login_user
from flask import flash, abort, request, render_template, redirect, url_for

from server.app import app, users_manager
from .forms import LoginForm, RegisterForm
from .users import User


@app.route("/login", methods=["GET", "POST"])
def authenticate_user():
    form = LoginForm(request.form)
    if request.method == "POST":

        if form.validate_on_submit():
            username = form.username.data
            password = form.password.data

            user: Optional[User] = users_manager.authorize(username, password)

            if user:
                login_user(user)
                return redirect(url_for("index_page"))
            else:
                flash("Username and/or password are not correct")

    return render_template("users/login.html", form=form)


@app.route("/register", methods=["GET", "POST"])
def register_user():
    form = RegisterForm(request.form)
    if request.method == "POST":
        if form.validate_on_submit():
            username = form.username.data
            password = form.password.data
            email = form.email.data
            fullname = form.fullname.data

            user: Optional[User] = users_manager.register(username, email, password, fullname)
            # TODO exception handling
            import pdb
            pdb.set_trace()
            login_user(user)
            return redirect(url_for("index_page"))

    return render_template("users/register.html", form=form)


@app.route("/users", methods=["GET"])
def users_list():
    pass


@app.route("/logout", methods=["GET"])
def logout():
    pass


@app.route("/user_profile", methods=["GET"])
def user_profile():
    pass




server/templates/base.html
<!doctype html>
<html>
  <head>
    <title>{% block title %}{% endblock %} - Flaskr</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--<link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.png') }}">-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/fontawesome-free-5.15.4-web/css/all.min.css') }}">
    <!--<script src="{{ url_for('static', filename='js/jquery-3.5.1.min.js') }}"></script>-->
    <!--<script src="{{ url_for('static', filename='js/knockout-3.5.1.js') }}"></script>-->
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">
          <i class="fas fa-bicycle"></i>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          {% if current_user.is_authenticated %}
          <li class="nav-item {% if 'services' in request.path %}active{% endif %}">
            <a class="nav-link" href="{{ url_for('services.services_list') }}">Services</a>
          </li>
          <li class="nav-item {% if 'configs' in request.path %}active{% endif %}">
            <a class="nav-link" href="{{ url_for('configs.configs_list') }}">Configs</a>
          </li>
          <li class="nav-item {% if 'users' in request.path %}active{% endif %}">
            <a class="nav-link" href="{{ url_for('users_list') }}">Users</a>
          </li>
          
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{current_user.email}}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href="{{ url_for('user_profile') }}">My Profile</a>
              {% if current_user.role == "admin" %}
              <a class="dropdown-item" href="{{ url_for('users.admin_dashboard') }}">Admin Dashboard</a>
              {% endif %}
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{{ url_for('logout') }}">Log Out</a>
            </div>
          </li>
          {% else %}
          <li class="nav-item {% if request.path == url_for('register_user') %}active{% endif %}">
            <a class="nav-link" href="{{ url_for('register_user') }}">Register</a>
          </li>
          <li class="nav-item {% if request.path == url_for('authenticate_user') %}active{% endif %}">
            <a class="nav-link" href="{{ url_for('authenticate_user') }}">Log In</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </nav>

    <div class="container mt-4">
      {% for primary_message in get_flashed_messages(category_filter=["primary"]) %}
      <div class="alert alert-primary alert-dismissible fade show" role="alert">
        {{ primary_message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endfor %}
      {% for secondary_message in get_flashed_messages(category_filter=["secondary"]) %}
      <div class="alert alert-secondary alert-dismissible fade show" role="alert">
        {{ secondary_message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endfor %}
      {% for success_message in get_flashed_messages(category_filter=["success"]) %}
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        {{ success_message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endfor %}
      {% for danger_message in get_flashed_messages(category_filter=["danger"]) %}
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        {{ danger_message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endfor %}
      {% for warning_message in get_flashed_messages(category_filter=["warning"]) %}
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {{ warning_message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endfor %}
      {% for info_message in get_flashed_messages(category_filter=["info"]) %}
      <div class="alert alert-info alert-dismissible fade show" role="alert">
        {{ info_message }}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% endfor %}
    </div>

    <div class="container">
      <div class="mt-5">
        <h1>{{ self.title() }}</h1>
        <hr>
      </div>
      {% block content %}{% endblock %}
    </div>

    <footer>
      <div class="container" style="margin-top:250px">
        <ul class="nav justify-content-center">
          <li class="nav-item"><a class="nav-link active" href="#">About</a></li>
          <li class="nav-item"><a class="nav-link active" href="#">FAQ</a></li>
          <li class="nav-item"><a class="nav-link active" href="#">Contact / Feedback</a></li>
        </ul>
      </div>
    </footer>
{#    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>#}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </body>
</html>

server/templates/formshelper.html
{% macro render_field(field) %}
{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <span class="text-danger">
    {% for error in field.errors %}
      {{ error }}
    {% endfor %}
    </span>
  {% endif %}
{% endmacro %}

{% macro checkbox(field, options) %}
<div class="form-check">
  {{ render_field(field, class="form-check-input", **options ) }}
  <label class="form-check-label" for="is_graphing">
    {{ field.label }}
  </label>
</div>
{% endmacro %}

{% macro select(field, options) %}
<div class="form-row">
    <div class="form-group col-md-4">
      {{ field.label }}
    </div>
    <div class="form-group col-md-8">
      {{ render_field(field, class="form-control", **options) }}
    </div>
</div>
{% endmacro %}

server/templates/index.html
{% extends "base.html" %}

{% block content %}
<div>
    <link rel= "stylesheet" type= "text/css" href= "{{ url_for('static', filename='styles/index.css') }}">
    <div class="welcomeblock">
        <h1>Welcome to the DistConfig!</h1>
    </div>
</div>
{% endblock %}

server/templates/users/login.html
{% extends "base.html" %}
{% block title %}Log in{% endblock %}
{% from "formshelper.html" import render_field %}

{% block content %}

<div class="row">
  <div class="col-md-6">
    <form action="{{ url_for('authenticate_user') }}" method="post">
        {{ form.csrf_token }}
        <div class="form-group">
          {{ form.username.label }}
          {{ render_field(form.username, class="form-control", placeholder="Email address") }}
        </div>
        <div class="form-group">
          {{ form.password.label }}
          {{ render_field(form.password, class="form-control", placeholder="Password") }}
        </div>
        <input type="submit" value="Log In" class="btn btn-lg btn-success">
        <p><br /><em><a href="/reset">Forgot your password?</a></em></p>
    </form>
  </div>
  <div class="col-md-6">
    <h2>DistConfig</h2>
    <p><em>Don't have an account yet?</em> <a href="{{ url_for('register_user') }}">Sign up for free!</a></p>
  </div>
</div>


{% endblock %}

server/templates/users/register.html
{% extends "base.html" %}
{% block title %}Register new account to work with distconfig{% endblock %}
{% from "formshelper.html" import render_field %}

{% block content %}

<div class="row">
  <div class="col-md-6">
    <form action="{{ url_for('register_user') }}" method="POST">
        {{ form.csrf_token }}
        <div class="form-group">
            {{ form.username.label }}
            {{ render_field(form.username, class="form-control", placeholder="Username") }}
        </div>
        <div class="form-group">
          {{ form.email.label }}
          {{ render_field(form.email, class="form-control", placeholder="Email address") }}
        </div>
        <div class="form-group">
          {{ form.password.label }}
          {{ render_field(form.password, class="form-control", placeholder="Password") }}
        </div>
        <div class="form-group">
          {{ form.confirm.label }}
          {{ render_field(form.confirm, class="form-control", placeholder="Confirm password") }}
        </div>
        <div class="form-group">
            {{ form.fullname.label }}
            {{ render_field(form.fullname, class="form-control", placeholder="Full name") }}
          </div>
        <input type="submit" value="Get Started!" class="btn btn-lg btn-success">
    </form>
  </div>
  <div class="col-md-6">
    <h3>Register new account</h3>
    <h4>No matter where your app are located.</h4>
    <p>With DistConfig you can work with independently of the app:</p>
    <p>
      <ul>
        <li>Dynamically change the configs.</li>
        <li>Don't be afraid of the leaks.</li>
        <li>Flexible system of controls, roles and permissions.</li>
      </ul>
    </p>
    <p></p>
  </div>
</div>

{% endblock %}